server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        http:
          endpoint: 0.0.0.0:14268

query_frontend:
  http_listen_port: 3100

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

storage_config:
  boltdb_shipper:
    active_index_directory: /tempo/index
    cache_location: /tempo/cache
    shared_store: filesystem
  filesystem:
    directory: /tempo/chunks

tracing:
  jaeger:
    enabled: true
    endpoint: http://tempo:14250
