pring.application.name=personalized_learning_db
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5433/personalized_learning_db
spring.datasource.username=admin
spring.datasource.password=ChangeMe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.main.allow-bean-definition-overriding=true
//spring.jackson.property-naming-strategy=SNAKE_CASE
spring.sql.init.schema-locations=classpath:/db/migration/entity.sql


